/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bitcamp.lms;

public class App {
 
    public static void main(String[] args) {
      int number = 1 ;
      String start ="2019-05-28";
      
      System.out.println("번호:"+ number);
      System.out.println("수업명: 자바프로젝트 실습");
      System.out.println("설명: 자바 프로젝트를 통한 자바 언어 활용법 익히기");
      System.out.println("시작일:"+start);
      System.out.println("종료일:2019-05-28");
      System.out.print("총수업시간:");
      System.out.println(1000+"시간");
      System.out.println("일수업시간 :8시간");
      
      
    }
}
